name: Build Realme SM4250 Kernel (Clang 11 + Stock Defconfig)

on:
  workflow_dispatch:
  push:
    branches:
      - stable   # Change this to your kernel branch if different

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 --branch stable https://github.com/Ponleuz12/kernel_realme_sm4250.git kernel_source

      - name: Setup Clang 11.0.1
        run: | 
          git clone --depth=1 https://github.com/techyminati/android_prebuilts_clang_host_linux-x86_clang-6443078 clang
          

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi libssl-dev make python3

      - name: Build Kernel
        working-directory: kernel_source
        run: bash ../build2.sh

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: kernel_source/Image.gz-dtb
